services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: simpul_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
      - ./backend/app/static:/app/static
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/simpul_dfir.db
      - TZ=Asia/Jakarta
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: simpul_frontend
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
    depends_on:
      - backend


